#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y emacs-nox curl tree unzip zip mosh aspell-en

cd $(dirname $0)
# Current Approach to humacs
git clone --recursive https://github.com/humacs/.emacs.d ~/.emacs.d

# Next Approach to humacs
# git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
# git clone https://github.com/humacs/.spacemacs.d
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmate.conf ~
# cp .tmux.conf ~

sudo cp hub /usr/local/bin

sudo wget -qO /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
